# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import contents_pb2 as contents__pb2


class ContentsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddFood = channel.unary_unary(
        '/Contents/AddFood',
        request_serializer=contents__pb2.Food.SerializeToString,
        response_deserializer=contents__pb2.FoodResp,
        )


class ContentsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddFood(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ContentsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddFood': grpc.unary_unary_rpc_method_handler(
          servicer.AddFood,
          request_deserializer=contents__pb2.Food,
          response_serializer=contents__pb2.FoodResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Contents', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
