# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contents.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contents.proto',
  package='SmartFridge.src.main.python',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63ontents.proto\x12\x1bSmartFridge.src.main.python\"\x14\n\x04\x66ood\x12\x0c\n\x04name\x18\x01 \x01(\t2[\n\x08\x43ontents\x12O\n\x07\x61\x64\x64\x66ood\x12!.SmartFridge.src.main.python.food\x1a!.SmartFridge.src.main.python.foodb\x06proto3')
)




_FOOD = _descriptor.Descriptor(
  name='food',
  full_name='SmartFridge.src.main.python.food',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SmartFridge.src.main.python.food.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['food'] = _FOOD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

food = _reflection.GeneratedProtocolMessageType('food', (_message.Message,), dict(
  DESCRIPTOR = _FOOD,
  __module__ = 'contents_pb2'
  # @@protoc_insertion_point(class_scope:SmartFridge.src.main.python.food)
  ))
_sym_db.RegisterMessage(food)



_CONTENTS = _descriptor.ServiceDescriptor(
  name='Contents',
  full_name='SmartFridge.src.main.python.Contents',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=69,
  serialized_end=160,
  methods=[
  _descriptor.MethodDescriptor(
    name='addfood',
    full_name='SmartFridge.src.main.python.Contents.addfood',
    index=0,
    containing_service=None,
    input_type=_FOOD,
    output_type=_FOOD,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTENTS)

DESCRIPTOR.services_by_name['Contents'] = _CONTENTS

# @@protoc_insertion_point(module_scope)
